language: c

sudo: true

env:
  global:
    - LUAROCKS=2.4.1
  matrix:
    - LUA=luajit     # latest stable version (2.0.4)


branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh

install:
  - sudo luarocks make luafanmicro-0.4-1.rockspec

script:
  - cd

after_success:
  - cd

notifications:
  email:
    on_success: change
    on_failure: always
